import React from "react";
import Head from "next/head";
export type Props = {
  title: string;
};
function CustomHead({ title }: Props): React.ReactElement {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default CustomHead;
